#!/bin/bash

echo Building...
if gcc src/*.cpp -lSDL2 -lm -lstdc++ -o bin/run; then
    echo Done!
    while true; do
        read -p "Run Program? (Y/n)" yn
        case $yn in
            [Yy]* ) ./bin/run; break;;
            [Nn]* ) exit;;
            * ) ./bin/run; break;;
        esac
    done
else
    echo Failed to compile...
fi